# fly.toml app configuration file generated for crimson-meadow-5050 on 2023-07-18T15:41:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crimson-meadow-5050"
primary_region = "atl"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[deploy]
release_command = "npm run migrate up"
